version: 0.2

phases:
  pre_build:
    commands:
      - $(aws ecr get-login-password --region us-east-2)
  build:
    commands:
      - docker build -t fast_api:latest .
      - docker tag fast_api:latest 399885010453.dkr.ecr.us-east-2.amazonaws.com/repo_two:fast_api
  post_build:
    commands:
      - docker push 3399885010453.dkr.ecr.us-east-2.amazonaws.com/repo_two:fast_api
      - printf '[{"name":my-taskdefinition-2,"imageUri":"%s"}]' 399885010453.dkr.ecr.us-east-2.amazonaws.com/repo_two:fast_api > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
